name: Ruby

on: push

jobs:
  build:
    name: 'test build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Build and test with Rake
      env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
